script: "./generate_api.rb"
deploy:
  provider: divshot
  api_key:
    secure: j4k6YEmsYwyqhIsbvdWMqGqkn+MV/R4tCuYJNZMO4CsTLohC3vrDqyF14Ph9NA/17frpk0EgiKajczATh9o4I3pu3q3l+tRP+3/qDHeeXeNRsRyCn+T2/DXoM9DFfXhqk7+nGDZ3bcPxms1Gi2LHCQB/jVWgVNKRLDzol6NSUAU=
  environment: production
  skip_cleanup: true
  on:
    repo: ctreatma/bjcp-static
